# Generated by Django 2.2 on 2021-05-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='des',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
